### ISSUE TITLE
Where is "uptime_formatter.h" ?

### ISSUE THREAD

**Issue by ivanpiter** [Whyzanet/WhyzaGC#2]
exit status 1
uptime_formatter.h: No such file or directory

**Comment by ivanpiter** [comment]
Thank you!
Uptime Library was not installed.
Next stuck:
E:\Arduino\libraries\TLog\src\MqttlogStream.cpp:22:10: fatal error: PubSubClient.h: No such file or directory

**Comment by Whyzanet** [comment]
Install library PubSubClient

**Comment by ivanpiter** [comment]
Great! 
Finally it is built.

**Comment by Whyzanet** [comment]
Great news.
Have fun !
